### ISSUE TITLE
add an example of how to put multiple suites in a module and use nested suites.

### ISSUE THREAD

**Issue by johntrandall** [theintern/intern-tutorial#14]
add an example of how to put multiple suites in a module and use nested suites.

Tutorial states the following, but doesn't show a syntax example:

    These pieces can be visualized in a hierarchy, like this:
    
    * test module
      * test suite
        * test suite
          * test case
            * ...
          * ...
        * test case
          * assertion
          * assertion
          * ...
        * ...
      * test suite
      * ...
    * test module
    * ...

**Comment by csnover** [comment]
Nesting suites is described in the [test interfaces](https://theintern.github.io/intern/#interface-overview) documentation in the user guide and those sections are linked from the tutorial, so I am going to close this for now, but please feel free to submit a PR if you would like to work it into the tutorial!
