### ISSUE TITLE
Links offline

### ISSUE THREAD

**Issue by sandrina-p** [theintern/intern-tutorial#31]
Guys, I'm starting learning Intern today and some of your links are off-line :(

https://theintern.github.io/intern/#what-is-intern

https://theintern.github.io/intern/#writing-unit-test

https://theintern.github.io/intern/#common-config

https://theintern.github.io/leadfoot/Command.html

Thanks :)

**Comment by jason0x43** [comment]
[GitHub status](https://status.github.com) reports that they're seeing an increase in erroneous 404 responses, so this is probably just a transient issue. I'm currently having trouble loading Intern pages, but the Leadfoot guide works fine, and some other people I've talked to aren't having any issues.

**Comment by sandrina-p** [comment]
Ah thank you! I didn't know that. Do u know why is that happen and when it
will be on again?

**Comment by dylans** [comment]
For what it's worth, this is working fine now, so was hopefully just a transitory GitHub issue.
