### ISSUE TITLE
How to use NullTunnel behind corporate proxy firewall?

### ISSUE THREAD

**Issue by NikitaTanwani** [theintern/intern-tutorial#38]
While running npm test(yarn test) after creating the unit test as mentioned in the tutorial, I am getting the following error. How do I resolve this ?

![image](https://user-images.githubusercontent.com/31532801/30049409-27fe94b4-9238-11e7-92e4-6498230c7606.png)

**Comment by jason0x43** [comment]
What does your `intern.json` file look like? Note that the [tunnel names in Intern 4](https://theintern.io/docs.html#Intern/4/docs/docs%2Fconfiguration.md/tunnel) have changed.

**Comment by NikitaTanwani** [comment]
This is what my intern.json file holds right now: (I added tunnel and capabilities though the tutorial doesn't mention it)

{
    "browser": {
        "loader": {
            "script": "systemjs"
        },
        "plugins": "_dist/src/system.config.js"
    },
    "environments": { "browserName": "chrome" },
	"suites": "_dist/tests/unit/hello.js",
	"tunnel": "NullTunnel",
	
	"capabilities": {
		"selenium-version": "3.5.3"
	}
}

**Comment by jason0x43** [comment]
As the docs mention, tunnel should be `'null'`. You probably don't need `capabilities` in this case since the remote system will likely be determining what selenium version is used (assuming there are even multiple versions available).

**Comment by NikitaTanwani** [comment]
It solved the problem. Thanks alot :)
