### ISSUE TITLE
Add a tutorial for non Sauce users

### ISSUE THREAD

**Issue by gaurav21r** [theintern/intern-tutorial#5]
Hey! I'm a long term contributor to Dojo. It's good to know it now uses Sauce Labs and theintern for testing.

I think I speak for a lot of people when I say that not all of us may have Open Source Projects or could afford Sauce Labs pricing. If we truly believe TheIntern should become a widespread testing framework, I think a tutorial on running functional tests using Selenium should also be added.

Here's a question from Bill Keese. Can we convert the answer into a tutorial? http://stackoverflow.com/questions/16414829/how-do-i-setup-selenium-2-server-so-intern-can-run-functional-tests-locally-on

**Comment by csnover** [comment]
Information in today’s [user guide](https://theintern.github.io/intern/) should be able to address questions about how to set up other kinds of servers or use other cloud hosting providers, so I will close this ticket.
